
server:
  port: 31001
spring:
  application:
    name: xc-service-manage-cms
  data:
    mongodb:
      url: localhost:27017
      database: xc_cms
  freemarker:
     cache: false #关闭模板缓存，方便测试settings:
     template_update_delay: 0
zuul:
  servlet-path=/:
